# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha Alangar
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha Alangar
    description : I might be small but you'd best believe I can do it all 🚀👽
    experience :
      - start : July 2025
        end : Present
        experience : AI Research Assistant
        place: VISA Research Lab (ASU)
        location: Remote
        summary: • Aiding PhD research into social health recommendation agents focusing on LLM based adaptive personalization<br/><br/>• Working on long term memory context retrieval with open-source MCPs and Agentic RAG, leveraging CrewAI
      - start : June 2024
        end : August 2024
        experience : Software Engineering Intern
        place: National Basketball Association (NBA)
        location: New York City, NY
        summary: • Worked on core frontend infrastructure for Sports News, Ads, Catalogs, Scores and Subscriptions on NBA.com<br/><br/>• Performed Tailwind to CSS codebase migrations and abstracted JavaScript serialization into separate packages<br/><br/>• Refactored core Python authentication REST APIs for League Pass subscriptions, and created a framework for granular control over ads serving logic in GraphQL
      - start : August 2023
        end : Present
        experience : Graduate
        place: Arizona State University
        location: Tempe, AZ
        summary: Master of Science<br/>Computer Science
      - start : August 2020
        end : June 2023
        experience : Software Engineer
        place: Target Corporation
        location: Bangalore, KA
        summary: • Search team at Target is responsible for search and recommendation on Target.com, managing the entire lifecycle from search input and autocomplete, to query completion, normalization, and query suggestions<br/><br/>• Touching Java, Kotlin, React, Docker, Kubernetes and Elasticsearch, I built and maintained enterprise grade cross-functional microservices with associated testing, observability and ops through Grafana and Kibana<br/><br/>• Improved user query suggestion ranking by leveraging search prefix prioritization, fuzzy matching and look-up tries, leading to large improvements in peak search transaction throughput<br/><br/>• Productionized a Kafka based Sequence Generator, serving as an efficient product catalog engine that consolidates information from various sources, for which I was recognized with an award<br/><br/>• Built pipelines to consolidate Kafka clusters and Redis cache in real-time for high availability during peak hours, and migrated sections of Target's tech stack from Java, Spring and MySQL to Kotlin, Micronaut and PostgreSQL<br/><br/>• Identified critical fields and re-indexed Target's fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Bangalore, KA
        summary: Bachelor of Engineering<br/>Computer Science and Engineering
      - start : May 2014
        end : May 2016
        experience : Pre-University
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 12th grade | 93.2%.
      - start : May 2002
        end : May 2014
        experience : High School
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 10th grade | CGPA 10.
    skills : # Unused
      - skill : JAVA / KOTLIN
        value : 90  # Percent value
      - skill : WEB DEVELOPMENT
        value : 85  # Percent value

  # Icons
  icons :
    email:  anushalngr@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab:
    bitbucket:
    google_plus:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
