# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha Alangar
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha Alangar
    description : I might be small but you'd best believe I can do it all 🚀👽
    experience :
      - start : June 2024
        end : August 2024
        experience : Software Engineering Intern
        place: NBA
        location: New York City, NY
        summary: • Working in the Direct-to-consumer Product Tech and Ops org, I built and maintained features on NBA.com, covering everything from sports news, advertising, athlete catalogs to live scores, subscriptions and live streaming<br/><br/>•Performed codebase migrations and component refactors, rewriting and abstracting serialization into a separate library, consolidating core APIs and debugging sign-in and auth flow bugs for League Pass subscriptions<br/><br/>•Fixed issues with SEO, CDN and concurrent sessions with VOD streaming, created a framework for granular control over ads criteria, along with several pipelines to synchronize build artifacts in across deployment environments
      - start : August 2023
        end : Present
        experience : Graduate
        place: Arizona State University
        location: Tempe, USA
        summary: Master of Science<br/>Computer Science
      - start : August 2020
        end : June 2023
        experience : Software Engineer
        place: Target
        location: Bangalore, KA
        summary: • Search Box and Facets team is responsible for AI powered search and recommendation on Target's platform, where I worked to optimize and improve search autocomplete, query normalization, query completion and facet suggestions<br/><br/>•Working with Java, Kotlin, React, Docker and Kubernetes, I improved user query suggestion ranking leveraging search prefix prioritization, fuzzy matching and look-up tries, resulting in higher peak transactions per second<br/><br/>•Developed an end-to-end Tcin Sequence Generator, an efficient product locator that identifies store locations of any product across all Target outlets leveraging Kafka and the Google Cloud Platform<br/><br/>•Built microservices for consolidating product information from different Kafka clusters as well as Redis cache in real-time for high data availability during peak hours, and migrated sections of Target’s tech stack from Java, Spring and MySQL to a distributed microservice based architecture using Kotlin, Micronaut and PostgreSQL<br/><br/>•Identified critical fields and re-indexed Target’s fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Bangalore, KA
        summary: Bachelor of Engineering<br/>Computer Science and Engineering
      - start : May 2014
        end : May 2016
        experience : Pre-University
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 12th grade | 93.2%.
      - start : May 2002
        end : May 2014
        experience : High School
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 10th grade | CGPA 10.
    skills : # Unused
      - skill : JAVA / KOTLIN
        value : 90  # Percent value
      - skill : WEB DEVELOPMENT
        value : 85  # Percent value

  # Icons
  icons :
    email:  anushalngr@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab:
    bitbucket:
    google_plus:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
