# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha A
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha Alangar
    description : I might be small but you'd best believe I can do it all 🚀👽
    experience :
      - start : August 2023
        end : Present
        experience : Graduate
        place: Arizona State University
        location: Tempe, USA
        summary: Master of Science<br/>Computer Science
      - start : August 2020
        end : June 2023
        experience : Software Engineer
        place: Target
        location: Bengaluru
        summary: Search | Backend / Full Stack Developer<br/><br/>•	As part of the Search Box and Facets team, I worked to optimize and improve search autocomplete, query normalization, query completion and product facet suggestion optimizations on the Target website, working on a wide variety of tech stacks incorporating Java, Kotlin, Kafka, GCP, and cloud native technologies.<br/><br/>•	Improved user query suggestion ranking leveraging search prefix prioritization, fuzzy matching and look-up tries, resulting in higher peak Transactions Per Hour.<br/><br/>•	Built Tcin Sequence Generator, an efficient product locator that identifies store locations of any given product across all Target outlets.<br/><br/>•	Developed a service that consolidates product information from different Kafka clusters as well as Redis cache in real time for high data availability during peak.<br/><br/>•	Worked on migrating Target’s tech stack from Java / Spring Boot / MySQL to Kotlin / Micronaut / PostgreSQL, and to a distributed micro service based architecture. <br/><br/>• Was instrumental in developing Target's company wide employee onboarding platform. <br/><br/>• Identified critical fields and re-indexed Target’s fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms.
      - start : Jan 2020
        end : Feb 2020
        experience : Web Development Internship
        place: Donti Technologies
        location: Bengaluru
        summary: Full Stack Developer<br/><br/>•	Developed a new company website with a comprehensive new interface using React, including a new shopping cart system.
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Electronic City Campus, Bengaluru
        summary: Bachelor of Engineering<br/>Computer Science and Engineering | 8.7 CGPA.
      - start : May 2014
        end : May 2016
        experience : Pre-University
        place: HAL Public School
        location: Bengaluru
        summary: CBSE 12th grade | 93.2%.
      - start : May 2002
        end : May 2014
        experience : High School
        place: HAL Public School
        location: Bengaluru
        summary: CBSE 10th grade | CGPA 10.
    skills :
      - skill : JAVA / KOTLIN
        value : 90  # Percent value
      - skill : WEB DEVELOPMENT
        value : 85  # Percent value

  # Icons
  icons :
    email:  anusha50898@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab:
    bitbucket:
    google_plus:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
