# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha Alangar
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha Alangar
    description : I might be small but you'd best believe I can do it all 🚀👽
    experience :
      - start : July 2025
        end : Present
        experience : Research Assistant
        place: VISA Research Lab - Arizona State University
        location: Remote
        summary: • Researching social health recommendation agents using OpenAI models, focusing on adaptive personalization<br/><br/>• Designing solutions for long term memory context retrieval with practical applications in Retrieval-Augmented Generation (RAG) for knowledge grounding and dialogue coherence
      - start : June 2024
        end : August 2024
        experience : Software Engineering Intern
        place: National Basketball Association (NBA)
        location: New York City, NY
        summary: • Worked on B2C features including Sports News, Ads, Catalogs, Scores, Subscriptions and streaming on NBA.com<br/><br/>• Performed Next.js and Tailwind codebase migrations, abstracting serialization into separate packages, and refactored core authentication APIs for League Pass subscriptions<br/><br/>• Resolved bugs with concurrent VOD streaming, created a framework for granular control over ads serving logic<br/><br/>• Improved user query suggestion ranking by leveraging search prefix prioritization, fuzzy matching, look-up tries and tensor decomposition, leading to large improvements in peak search transaction throughput<br/><br/>• Productionized a Kafka based Tcin Sequence Generator, serving as an efficient inventory locator that identifies stores containing inventory of a product SKU across all Target outlets<br/><br/>• Built pipelines to consolidate Kafka clusters and Redis cache in real-time for high availability during peak hours, and migrated sections of Target’s tech stack from Java, Spring and MySQL to Kotlin, Micronaut and PostgreSQL<br/><br/>• Identified critical fields and re-indexed Target’s fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms
      - start : August 2023
        end : Present
        experience : Graduate
        place: Arizona State University
        location: Tempe, AZ
        summary: Master of Science<br/>Computer Science
      - start : August 2020
        end : June 2023
        experience : R&D Software Engineer
        place: Target Corporation
        location: Bangalore, KA
        summary: • Search team at Target is responsible for AI powered search and recommendation on Target.com, managing the entire lifecycle from search input and autocomplete, to query completion, normalization, and redirection<br/><br/>• Built and maintained enterprise grade cross-functional microservices touching Java, Kotlin, React, Docker, Kubernetes and Elasticsearch, along with associated observability and ops<br/><br/>• Improved user query suggestion ranking by leveraging search prefix prioritization, fuzzy matching, look-up tries and tensor decomposition, leading to large improvements in peak search transaction throughput<br/><br/>• Productionized a Kafka based Tcin Sequence Generator, serving as an efficient inventory locator that identifies stores containing inventory of a product SKU across all Target outlets<br/><br/>• Built pipelines to consolidate Kafka clusters and Redis cache in real-time for high availability during peak hours, and migrated sections of Target’s tech stack from Java, Spring and MySQL to Kotlin, Micronaut and PostgreSQL<br/><br/>• Identified critical fields and re-indexed Target’s fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Bangalore, KA
        summary: Bachelor of Engineering<br/>Computer Science and Engineering
      - start : May 2014
        end : May 2016
        experience : Pre-University
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 12th grade | 93.2%.
      - start : May 2002
        end : May 2014
        experience : High School
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 10th grade | CGPA 10.
    skills : # Unused
      - skill : JAVA / KOTLIN
        value : 90  # Percent value
      - skill : WEB DEVELOPMENT
        value : 85  # Percent value

  # Icons
  icons :
    email:  anushalngr@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab:
    bitbucket:
    google_plus:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
