# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha A
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha A
    description : An ok kid from Pallet Town, with a brand new world to see 👽
    experience :
      - start : August 2020
        end : Now
        experience : Software Engineer
        place: Target
        location: Bengaluru
        summary: A summary of what I did, etc. <br/>Next line.
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Electronic City Campus, Bengaluru
        summary: Bachelor of Engineering, Information Science & Engineering, 8.69 CGPA.
      - start : May 2002
        end : May 2016
        experience : Student
        place: HAL Public School
        location: Bengaluru
        summary: CBSE, 10th grade CGPA 10, 12th grade 93.2%.
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : SOME OTHER SKILL
        value : 55  # Percent value
        
  # Icons
  icons :
    email:  anusha50898@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: porgdragoon
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
