# Site Settings
baseurl: ""
url : "https://anushaa51.github.io"

# Blog Settings
theme_settings :
  title : Anusha Alangar
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/portrait.jpg
    username : Anusha Alangar
    description : I might be small but you'd best believe I can do it all 🚀👽
    experience :
      - start : June 2024
        end : August 2024
        experience : Software Engineering Intern
        place: National Basketball Association
        location: New York City, NY
        summary: • Worked in the team that builds and maintains functionality on NBA.com, covering everything from NBA news, advertising, athlete catalogs to live scores, subscriptions and live streaming<br/><br/>• Executed code refactors including Tailwind to pure CSS migration, moving common serialization functions to a separate library, consolidating core APIs and debugging sign-in and auth flow bugs for League Pass subscriptions<br/><br/>• Updated various components on NBA.com, fixing issues in concurrent sessions on VODs with tests and coverage<br/><br/>• Tweaked CDN and SEO infrastructure, created a framework for controlling advertising criteria at a more granular level and created several pipelines to synchronize build artifacts in different deployment environments
      - start : August 2023
        end : Present
        experience : Graduate
        place: Arizona State University
        location: Tempe, USA
        summary: Master of Science<br/>Computer Science
      - start : August 2020
        end : June 2023
        experience : Software Engineer
        place: Target
        location: Bangalore, KA
        summary: • As part of the Search Box and Facets team, I worked to optimize and improve search autocomplete, query normalization, query completion and product facet suggestions on the Target website<br/><br/>• Improved user query suggestion ranking leveraging search prefix prioritization, fuzzy matching and look-up tries, resulting in higher peak transactions per second<br/><br/>• Built Tcin Sequence Generator, an efficient product locator that identifies store locations of any given product across all Target outlets leveraging Kafka and GCP<br/><br/>• Developed a service that consolidates product information from different Kafka clusters as well as Redis cache in real time for high data availability during peak<br/><br/>• Worked on migrating Target’s tech stack from Java, Spring and MySQL to a distributed microservice based architecture using Kotlin, Micronaut and PostgreSQL<br/><br/>• Identified critical fields and re-indexed Target’s fork of Metabase that interfaces with MongoDB, resulting in reduced time taken to visualize data from over a minute down to sub 1000ms
      - start : Jan 2020
        end : Feb 2020
        experience : Web Development Internship
        place: Donti Technologies
        location: Bangalore, KA
        summary: Full Stack<br/><br/>• Developed a new company website with a comprehensive new interface using React, including a new shopping cart system.
      - start : August 2016
        end : August 2020
        experience : Undergraduate
        place: PES University
        location: Bangalore, KA
        summary: Bachelor of Engineering<br/>Computer Science and Engineering
      - start : May 2014
        end : May 2016
        experience : Pre-University
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 12th grade | 93.2%.
      - start : May 2002
        end : May 2014
        experience : High School
        place: HAL Public School
        location: Bangalore, KA
        summary: CBSE 10th grade | CGPA 10.
    skills : # Unused
      - skill : JAVA / KOTLIN
        value : 90  # Percent value
      - skill : WEB DEVELOPMENT
        value : 85  # Percent value

  # Icons
  icons :
    email:  anushalngr@gmail.com
    linkedin:  https://www.linkedin.com/in/anushaa51/
    github: anushaa51
    gitlab:
    bitbucket:
    google_plus:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
